Sprint 5/step 1
2web/ya-react-burger pull request #7
Opened 2023-03-24 08:57 UTC by 2web

2023-03-24 10:36 UTC, andryxxa93 requested changes
Здравствуйте! Отличная работа 👍 
- Очень хорошая типизация функций и компонентов
- Хорошая типизация хранилища
- Сокеты открываются и закрываются согласно тех заданию.

Так держать!

Но есть пару замечаний, который необходимо исправить:
- `propTypes` необходимо отовсюду удалить, теперь используется только `typescript`
- Поправьте тип у `NavItem` - (см. подробнее комментарий к pull-request)

**Можно лучше**
- Нужно организовать раздельное хранение данных в хранилище Redux, получаемых от сокета для авторизованного и неавторизованного пользователей.
- Нужно рассматривать разный набор экшенов при работе с сокетом для авторизованного и неавторизованного пользователя, и задавать свой набор экшенов как аргумент при вызовах миддлвара wsMiddleware в configureStore.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-24 10:36 UTC, andryxxa93 commented on src/components/app/app.tsx
> +          <Route path="/ingredients/:id">
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-03-24 10:36 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.tsx
> +  const constructorBun = useAppSelector((store) => store.constructorReducer.constructorBun);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-03-24 10:36 UTC, andryxxa93 commented on src/components/header/header-nav-item/header-nav-item.tsx
> +const NavItem = (props: { to: LocationDescriptor<unknown> | ((location: Location<unknown>) => LocationDescriptor<unknown>); children: string | number | boolean | ReactElement<any, string | JSXElement
**Необходимо исправить**
Так типы не стоит писать - во-первых их просто невозможно прочитать и понять что тут конкретно необходимо. Во-вторых в этом нет никакой необходимости. Данный компонент просто типизируется
`props: {to: string, children: ReactNode, value: string}`

2023-03-24 10:36 UTC, andryxxa93 commented on src/components/order/detail/detail.tsx
> +    store.wReducer.messages?.orders.find(
**Можно лучше**
Рекомендую возвращать из стора все заказы а уже потом в отдельной переменной используя `useMemo` находить нужный. Это уменьшит количество ненужных срабатывай `useSelector`

2023-03-24 10:36 UTC, andryxxa93 commented on src/store/middleware/socket-middleware.ts
> +        socket.onmessage = (event) => {
**Можно лучше**
Необходимо добавить проверку при получении сообщения от сокета. Eсли токен протух и приходит поле message 'Invalid or missing token' то его необходимо обновить через refreshToken.

2023-03-24 10:36 UTC, andryxxa93 commented on src/store/reducers/user-reducer.ts
> +      localStorage.removeItem("refreshToken");
**Можно лучше**
Желательно ключи для localStorage так же записывать в константы - так удобнее и сложнее ошибиться.

2023-03-26 09:03 UTC, andryxxa93 requested changes
- Поправьте тип у NavItem - (см. подробнее комментарий к pull-request)
И ваша работа будет принята!

2023-03-26 12:29 UTC, 2web commented
> * Поправьте тип у NavItem - (см. подробнее комментарий к pull-request)
>   И ваша работа будет принята!
Добрый день. Я поправил в предыдущем коммите тип у NavItem
![navitem](https://user-images.githubusercontent.com/1179883/227775719-ff27e301-7340-4185-8d75-3433aaa11d60.jpg)

2023-03-27 06:00 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-27 06:01 UTC, andryxxa93 commented
> > * Поправьте тип у NavItem - (см. подробнее комментарий к pull-request)
> >   И ваша работа будет принята!
> >   Добрый день. Я поправил в предыдущем коммите тип у NavItem
> >   ![navitem](https://user-images.githubusercontent.com/1179883/227775719-ff27e301-7340-4185-8d75-3433aaa11d60.jpg)

Прошу прощения - не в тот коммит посмотрел.

2023-03-27 06:41 UTC, merged